apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-go
  name: deploy-go
  namespace: space-gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-go
  template:
    metadata:
      labels:
        app: deploy-go
    spec:
      containers:
        - image: marved/go-gcp:latest
          name: go-kube
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-go
  name: svc-go
  namespace: space-gcp
spec:
  type: LoadBalancer
  ports:
    - name: svc-go
      port: 80
      protocol: TCP
  selector:
    app: deploy-go
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ingress-go
#  namespace: space-gcp
#spec:
#  ingressClassName: nginx
#  rules:
#    - host: load.sopes.tk
#      http:
#        paths:
#          - backend:
#              service:
#                name: svc-go
#                port:
#                  number: 80
#            path: /
#            pathType: Prefix
